package jbc.timesheet.model;

public enum Action {
    TIMESHEET_SUBMIT,
    TIMESHEET_CANCEL_SUBMIT,
    TIMESHEET_APPROVE,
    TIMESHEET_REJECT,
    TIMESHEET_REVISE_DECISION,
    TIMESHEET_CREATE,
    TIMESHEET_UPDATE,
    TIMESHEET_DELETE
}
